# Generated by Django 5.2 on 2025-04-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationsession',
            name='operator',
        ),
    ]
