# Generated by Django 5.0.2 on 2025-04-16 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_calibrationsession_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='HydraulicSystemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pressure_sensors', models.JSONField()),
                ('motor_power', models.JSONField()),
                ('volume_flow', models.JSONField()),
                ('temperature', models.JSONField()),
                ('vibration', models.JSONField()),
                ('efficiency', models.JSONField()),
                ('cooling_efficiency', models.JSONField()),
                ('cooling_power', models.JSONField()),
                ('cooler_condition', models.FloatField()),
                ('valve_condition', models.FloatField()),
                ('pump_leakage', models.IntegerField()),
                ('accumulator_pressure', models.FloatField()),
                ('is_stable', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Hydraulic System Data',
                'verbose_name_plural': 'Hydraulic System Data',
            },
        ),
        migrations.CreateModel(
            name='WeldQualityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_file', models.FileField(upload_to='weld_models/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('classes', models.JSONField(default=list)),
                ('input_shape', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='WeldInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='weld_inspections/')),
                ('prediction', models.CharField(choices=[('bad_welding', 'Bad Welding'), ('crack', 'Crack'), ('excess_reinforcement', 'Excess Reinforcement'), ('good_welding', 'Good Welding'), ('porosity', 'Porosity'), ('spatters', 'Spatters')], max_length=50)),
                ('confidence', models.FloatField()),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.weldqualitymodel')),
            ],
        ),
    ]
