from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('joint-types/', views.joint_type_list, name='joint_type_list'),
    path('joint-types/create/', views.joint_type_create, name='joint_type_create'),
    path('joint-types/<int:pk>/', views.joint_type_detail, name='joint_type_detail'),
    path('joint-types/<int:pk>/update/', views.joint_type_update, name='joint_type_update'),
    path('joint-types/<int:pk>/delete/', views.joint_type_delete, name='joint_type_delete'),
    path('sessions/', views.session_list, name='session_list'),
    path('sessions/create/', views.session_create, name='session_create'),
    path('sessions/<int:pk>/', views.session_detail, name='session_detail'),
    path('sessions/<int:pk>/update/', views.session_update, name='session_update'),
    path('sessions/<int:pk>/delete/', views.session_delete, name='session_delete'),
    path('sessions/download-data/', views.download_kaggle_data, name='download_kaggle_data'),
    path('models/', views.model_list, name='model_list'),
    path('models/create/', views.model_create, name='model_create'),
    path('models/<int:pk>/', views.model_detail, name='model_detail'),
    path('models/<int:pk>/update/', views.model_update, name='model_update'),
    path('models/<int:pk>/delete/', views.model_delete, name='model_delete'),
    path('models/<int:pk>/predict/', views.model_predict, name='model_predict'),
    path('sensor-data/', views.sensor_data_list, name='sensor_data_list'),
    path('sensor-data/create/', views.sensor_data_create, name='sensor_data_create'),
    path('sensor-data/<int:pk>/', views.sensor_data_detail, name='sensor_data_detail'),
    path('sensor-data/<int:pk>/update/', views.sensor_data_update, name='sensor_data_update'),
    path('sensor-data/<int:pk>/delete/', views.sensor_data_delete, name='sensor_data_delete'),
    path('hydraulic/', views.hydraulic_data_list, name='hydraulic_data_list'),
    path('hydraulic/<int:pk>/', views.hydraulic_data_detail, name='hydraulic_data_detail'),
    path('hydraulic/import/', views.import_hydraulic_data, name='import_hydraulic_data'),
    path('visualization/', views.visualization, name='visualization'),
    path('weld/train/', views.train_weld_model, name='train_weld_model'),
    path('weld/model/<int:pk>/', views.weld_model_detail, name='weld_model_detail'),
    path('weld/predict/<int:pk>/', views.predict_weld_quality, name='predict_weld_quality'),
    path('analysis/', views.analyze_data, name='analyze_data'),
] 